task import_orgs: :environment do 
  orgs = [
      {
          "Organisation": "met Office Wattisham",
      "No of employees": "10",
      "Sector": "Public",
      "Contact Name": "Claire Ellis",
      "Role": "Operational Meteorologise",
      "Tel number": "01449 728227",
      "Email": "claire.ellis@metoffice.gov.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "3",
      "No of WE placement in next 12 months": "1",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Norse",
      "No of employees": "6000",
      "Sector": "Facities Management, Care",
      "Contact Name": "Samantha Delcoure",
      "Role": "Recruitment Manager",
      "Tel number": "",
      "Email": "samantha.delcoure@ncsgrp.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 50,
      "Proportion to workforce": "1%",
      "No of apprentices in next 12 months": 100,
      "Proportion to workforce in next 12 months": "2%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Norse",
      "No of employees": "6000",
      "Sector": "Facities Management, Care",
      "Contact Name": "Samantha Delcoure",
      "Role": "Recruitment Manager",
      "Tel number": "",
      "Email": "samantha.delcoure@ncsgrp.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "35",
      "No of WE placement in next 12 months": "100",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Norse",
      "No of employees": "6000",
      "Sector": "Facities Management, Care",
      "Contact Name": "Samantha Delcoure",
      "Role": "Recruitment Manager",
      "Tel number": "",
      "Email": "samantha.delcoure@ncsgrp.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "2",


  },
      {
          "Organisation": "Rubyleaf Ltd",
      "No of employees": "4",
      "Sector": "Business Services",
      "Contact Name": "David Martin",
      "Role": "Director",
      "Tel number": "07411 444141",
      "Email": "dmartin@rubyleaf.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 0,
      "Proportion to workforce": "0",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "20",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Rubyleaf Ltd",
      "No of employees": "4",
      "Sector": "Business Services",
      "Contact Name": "David Martin",
      "Role": "Director",
      "Tel number": "07411 444141",
      "Email": "dmartin@rubyleaf.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Whitespace",
      "No of employees": "30",
      "Sector": "Creative Design",
      "Contact Name": "Camilla Haycock",
      "Role": "Group Officer Manager",
      "Tel number": "01473 215656",
      "Email": "Camilla@jacobbaileygroup.com",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "12",
      "No of WE placement in next 12 months": "15",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Lola Stafford Consulting Ltd",
      "No of employees": "3",
      "Sector": "Training",
      "Contact Name": "Jacqui Starling",
      "Role": "Director",
      "Tel number": "07806 392254",
      "Email": "jacqui@lolastaffordconsulting.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Suffolk New College",
      "No of employees": "450",
      "Sector": "Further Education",
      "Contact Name": "Viv Gillespie",
      "Role": "Principal",
      "Tel number": "01473 382454",
      "Email": "vivgillespie@suffolk.ac.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 20,
      "Proportion to workforce": "4%",
      "No of apprentices in next 12 months": 2,
      "Proportion to workforce in next 12 months": "5",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Suffolk New College",
      "No of employees": "450",
      "Sector": "Futher Education",
      "Contact Name": "Viv Gillespie",
      "Role": "Principal",
      "Tel number": "01473 382454",
      "Email": "vivgillespie@suffolk.ac.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "25",
      "No of WE placement in next 12 months": "30",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Hoseasons",
      "No of employees": "280",
      "Sector": "Tourism",
      "Contact Name": "Matt Smith",
      "Role": "Head of HR",
      "Tel number": "",
      "Email": "matt.smith@hoseasons.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 12,
      "Proportion to workforce": "4%",
      "No of apprentices in next 12 months": 12,
      "Proportion to workforce in next 12 months": "5",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Hoseasons",
      "No of employees": "280",
      "Sector": "Tourism",
      "Contact Name": "Matt Smith",
      "Role": "Head of HR",
      "Tel number": "",
      "Email": "matt.smith@hoseasons.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "8",
      "No of WE placement in next 12 months": "8",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Spirit Motorsport",
      "No of employees": "0",
      "Sector": "Motorsports",
      "Contact Name": "John Cowan",
      "Role": "Teamprincipal",
      "Tel number": "07899 093794",
      "Email": "Teamprincipal@Spirit-Motorsport.com",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 0,
      "Proportion to workforce": "N/A",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "20",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Spirit Motorsport",
      "No of employees": "0",
      "Sector": "Motorsports",
      "Contact Name": "John Cowan",
      "Role": "Teamprincipal",
      "Tel number": "07899 093794",
      "Email": "Teamprincipal@Spirit-Motorsport.com",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "0",
      "No of WE placement in next 12 months": "1",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Spirit Motorsport",
      "No of employees": "0",
      "Sector": "Motorsports",
      "Contact Name": "John Cowan",
      "Role": "Teamprincipal",
      "Tel number": "07899 093794",
      "Email": "Teamprincipal@Spirit-Motorsport.com",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Kingfisher Consultants Limited",
      "No of employees": "2",
      "Sector": "Employment Law",
      "Contact Name": "Angel Doyle",
      "Role": "Head of Operations",
      "Tel number": "07581 057550",
      "Email": "angel.doyle@kingfisherhr.com",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 0,
      "Proportion to workforce": "",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "50%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Kingfisher Consultants Limited",
      "No of employees": "2",
      "Sector": "Employment Law",
      "Contact Name": "Angel Doyle",
      "Role": "Head of Operations",
      "Tel number": "07581 057550",
      "Email": "angel.doyle@kingfisherhr.com",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "1",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Suffolk Chamber of Commerce",
      "No of employees": "33",
      "Sector": "Business Services",
      "Contact Name": "Ashleigh Seymour-Rutherford",
      "Role": "Assistant to the CEO",
      "Tel number": "01473 694807",
      "Email": "ashleigh@suffolkchamber.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 1,
      "Proportion to workforce": "3%",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "6",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Suffolk Chamber of Commerce",
      "No of employees": "33",
      "Sector": "Business Services",
      "Contact Name": "Ashleigh Seymour-Rutherford",
      "Role": "Assistant to the CEO",
      "Tel number": "01473 694807",
      "Email": "ashleigh@suffolkchamber.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "4",
      "No of WE placement in next 12 months": "4",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Suffolk Chamber of Commerce",
      "No of employees": "33",
      "Sector": "Business Services",
      "Contact Name": "Ashleigh Seymour-Rutherford",
      "Role": "Assistant to the CEO",
      "Tel number": "01473 694807",
      "Email": "ashleigh@suffolkchamber.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "2",


  },
      {
          "Organisation": "Access Community Trust",
      "No of employees": "68",
      "Sector": "VCS",
      "Contact Name": "Emma Ratzer",
      "Role": "Chief Executive",
      "Tel number": "01502 527204",
      "Email": "emma.ratzer@accessct.org",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 4,
      "Proportion to workforce": "5%",
      "No of apprentices in next 12 months": 4,
      "Proportion to workforce in next 12 months": "10%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Access Community Trust",
      "No of employees": "68",
      "Sector": "VCS",
      "Contact Name": "Emma Ratzer",
      "Role": "Chief Executive",
      "Tel number": "01502 527204",
      "Email": "emma.ratzer@accessct.org",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "4",
      "No of WE placement in next 12 months": "8",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Smart Garden Offices",
      "No of employees": "40",
      "Sector": "Manufacturing",
      "Contact Name": "Michelle Wootton",
      "Role": "Marketing Manager",
      "Tel number": "01473 833997",
      "Email": "michelle@smartgardenoffices.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 6,
      "Proportion to workforce": "15%%",
      "No of apprentices in next 12 months": 2,
      "Proportion to workforce in next 12 months": "20%%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Smart Garden Offices",
      "No of employees": "40",
      "Sector": "Manufacturing",
      "Contact Name": "Michelle Wootton",
      "Role": "Marketing Manager",
      "Tel number": "01473 833997",
      "Email": "michelle@smartgardenoffices.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "1",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Maids Head Hotel",
      "No of employees": "80",
      "Sector": "Hotel",
      "Contact Name": "Andrew Shorthose",
      "Role": "Operations Manager",
      "Tel number": "01603 209955",
      "Email": "operations@maidsheadhotel.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 1,
      "Proportion to workforce": "1.25%%",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "1.25%%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Maids Head Hotel",
      "No of employees": "80",
      "Sector": "Hotel",
      "Contact Name": "Andrew Shorthose",
      "Role": "Operations Manager",
      "Tel number": "01603 209955",
      "Email": "operations@maidsheadhotel.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "8",
      "No of WE placement in next 12 months": "8-10",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Maids Head Hotel",
      "No of employees": "80",
      "Sector": "Hotel",
      "Contact Name": "Andrew Shorthose",
      "Role": "Operations Manager",
      "Tel number": "01603 209955",
      "Email": "operations@maidsheadhotel.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Ipswich Building Society",
      "No of employees": "134",
      "Sector": "Financial",
      "Contact Name": "Ian A Brighton",
      "Role": "General Manager Operations",
      "Tel number": "01473 278471",
      "Email": "ianbrighton@ibs.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 5,
      "Proportion to workforce": "4%%",
      "No of apprentices in next 12 months": 5,
      "Proportion to workforce in next 12 months": "4%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Ipswich Building Society",
      "No of employees": "134",
      "Sector": "Financial",
      "Contact Name": "Ian A Brighton",
      "Role": "General Manager Operations",
      "Tel number": "01473 278471",
      "Email": "ianbrighton@ibs.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "6",
      "No of WE placement in next 12 months": "6",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Conga Limited",
      "No of employees": "5",
      "Sector": "Transport",
      "Contact Name": "Graham Kill",
      "Role": "Director",
      "Tel number": "07518 189802",
      "Email": "graham.kill@conga.io",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "1",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "The Mix Stowmarket",
      "No of employees": "12",
      "Sector": "Charity",
      "Contact Name": "Neil Serjeant",
      "Role": "CEO",
      "Tel number": "01449 745130",
      "Email": "neil@themixstowmarket.com",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Warren Services",
      "No of employees": "90",
      "Sector": "Engineering",
      "Contact Name": "Estee Ross",
      "Role": "HR Manager",
      "Tel number": "07769 208720",
      "Email": "estee@warrenservices.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 2,
      "Proportion to workforce": "2%",
      "No of apprentices in next 12 months": 3,
      "Proportion to workforce in next 12 months": "3%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Warren Services",
      "No of employees": "90",
      "Sector": "Engineering",
      "Contact Name": "Estee Ross",
      "Role": "HR Manager",
      "Tel number": "07769 208720",
      "Email": "estee@warrenservices.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "10",
      "No of WE placement in next 12 months": "15",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Warren Services",
      "No of employees": "90",
      "Sector": "Engineering",
      "Contact Name": "Estee Ross",
      "Role": "HR Manager",
      "Tel number": "07769 208720",
      "Email": "estee@warrenservices.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Adnams PLC",
      "No of employees": "435",
      "Sector": "Consumer Goods and Services",
      "Contact Name": "Sadie Lofthouse",
      "Role": "Head of Human Resources",
      "Tel number": "01502 727200",
      "Email": "sadie.lofthouse@adnams.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 2,
      "Proportion to workforce": "1%",
      "No of apprentices in next 12 months": 4,
      "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Adnams PLC",
      "No of employees": "435",
      "Sector": "Consumer Goods and Services",
      "Contact Name": "Sadie Lofthouse",
      "Role": "Head of Human Resources",
      "Tel number": "01502 727200",
      "Email": "sadie.lofthouse@adnams.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "14",
      "No of WE placement in next 12 months": "20",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Adnams PLC",
      "No of employees": "435",
      "Sector": "Consumer Goods and Services",
      "Contact Name": "Sadie Lofthouse",
      "Role": "Head of Human Resources",
      "Tel number": "01502 727200",
      "Email": "sadie.lofthouse@adnams.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "2",


  },
      {
          "Organisation": "Dayle Bayliss Associates LLP",
      "No of employees": "2",
      "Sector": "Construction",
      "Contact Name": "Dayle Bayliss",
      "Role": "Partner",
      "Tel number": "07930 135821",
      "Email": "dayle@daylebayliss.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Itron (U.K.) Ltd",
      "No of employees": "35",
      "Sector": "Manufacturing",
      "Contact Name": "Rachel George",
      "Role": "Finance and Personnel Manager",
      "Tel number": "01493 601144",
      "Email": "r.george@noritake-itron.com",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 2,
      "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Itron (U.K.) Ltd",
      "No of employees": "35",
      "Sector": "Manufacturing",
      "Contact Name": "Rachel George",
      "Role": "Finance and Personnel",
      "Tel number": "01493 601144",
      "Email": "r.george@noritake-itron.com",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "3",
      "No of WE placement in next 12 months": "4",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Norfolk Chamber of Commerce",
      "No of employees": "15",
      "Sector": "Membership Organisation",
      "Contact Name": "Caroline Williams",
      "Role": "Chief Executive",
      "Tel number": "01603 729701",
      "Email": "cw@norfolkchamber.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 1,
      "Proportion to workforce": "6%",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "13%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Norfolk Chamber of Commerce",
      "No of employees": "15",
      "Sector": "Membership Organisation",
      "Contact Name": "Caroline Williams",
      "Role": "Chief Executive",
      "Tel number": "01603 729701",
      "Email": "cw@norfolkchamber.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "0",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Apprenticeships Norfolk",
      "No of employees": "5000+",
      "Sector": "Local Government",
      "Contact Name": "Paul Wright",
      "Role": "Apprenticeships Strategy Manager",
      "Tel number": "01603 638463",
      "Email": "paul.wright@norfolk.gov.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 4,
      "Proportion to workforce": "1%",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "2%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Apprenticeships Norfolk",
      "No of employees": "5000+",
      "Sector": "Local Government",
      "Contact Name": "Paul Wright",
      "Role": "Apprenticeships Strategy Manager",
      "Tel number": "01603 638463",
      "Email": "paul.wright@norfolk.gov.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "1",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Apprenticeships Norfolk",
      "No of employees": "5000+",
      "Sector": "Local Government",
      "Contact Name": "Paul Wright",
      "Role": "Apprenticeships Strategy Manager",
      "Tel number": "01603 638463",
      "Email": "paul.wright@norfolk.gov.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "R G Carter Ltd",
      "No of employees": "500",
      "Sector": "Construction",
      "Contact Name": "Saul Humphrey",
      "Role": "Regional Director",
      "Tel number": "01603 867355",
      "Email": "saul.humphrey@rgcarter.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 67,
      "Proportion to workforce": "6%",
      "No of apprentices in next 12 months": 15,
      "Proportion to workforce in next 12 months": "7%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "R G Carter Ltd",
      "No of employees": "500",
      "Sector": "Construction",
      "Contact Name": "Saul Humphrey",
      "Role": "Regional Director",
      "Tel number": "01603 867355",
      "Email": "saul.humphrey@rgcarter.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": ">25",
      "No of WE placement in next 12 months": ">50",
      "No of EAs in company": "",


  },
      {
          "Organisation": "R G Carter Ltd",
      "No of employees": "500",
      "Sector": "Construction",
      "Contact Name": "Saul Humphrey",
      "Role": "Regional Director",
      "Tel number": "01603 867355",
      "Email": "saul.humphrey@rgcarter.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "0 but V interested",


  },
      {
          "Organisation": "Norfolk Training Service",
      "No of employees": "98",
      "Sector": "Education and Training",
      "Contact Name": "James Mason",
      "Role": "Commercial Director",
      "Tel number": "01603 259900",
      "Email": "james.mason@norfolktrainingservices.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 4,
      "Proportion to workforce": "4%",
      "No of apprentices in next 12 months": 3,
      "Proportion to workforce in next 12 months": "6%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Norfolk Training Service",
      "No of employees": "98",
      "Sector": "Education and Training",
      "Contact Name": "James Mason",
      "Role": "Commercial Director",
      "Tel number": "01603 259900",
      "Email": "james.mason@norfolktrainingservices.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "1",
      "No of WE placement in next 12 months": "3",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Norfolk Training Service",
      "No of employees": "98",
      "Sector": "Education and Training",
      "Contact Name": "James Mason",
      "Role": "Commercial Director",
      "Tel number": "01603 259900",
      "Email": "james.mason@norfolktrainingservices.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "0",


  },
      {
          "Organisation": "Morgan Sindall Construction and Infrastructure Ltd (East Anglia Offices)",
      "No of employees": "114",
      "Sector": "Construction",
      "Contact Name": "Helen Clements",
      "Role": "Community Investment Advisor",
      "Tel number": "07816 330706",
      "Email": "helen.clements@morgansindall.com",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "10",
      "No of WE placement in next 12 months": "20",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Morgan Sindall Construction and Infrastructure Ltd (East Anglian Offices)",
      "No of employees": "114",
      "Sector": "Construction",
      "Contact Name": "Helen Clements",
      "Role": "Community Investment Adviser",
      "Tel number": "07816 330706",
      "Email": "helen.clements@morgansindall.com",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "1",


  },
      {
          "Organisation": "Future Marine Services Ltd",
      "No of employees": "20",
      "Sector": "Marine",
      "Contact Name": "Nicola Finch",
      "Role": "HR & Corporate Support Manager",
      "Tel number": "01379 640021",
      "Email": "nicola.finch@safests.com",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "2",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "The Mason Trust",
      "No of employees": "3",
      "Sector": "Charity",
      "Contact Name": "Nicola Finch",
      "Role": "Trustee",
      "Tel number": "01379 650041",
      "Email": "nicola.finch@themasontrust.org",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "1",
      "No of WE placement in next 12 months": "1",
      "No of EAs in company": "",


  },
      {
          "Organisation": "WS Training Ltd",
      "No of employees": "96",
      "Sector": "Training",
      "Contact Name": "Sally Carter",
      "Role": "Director of Operations",
      "Tel number": "01284 788005",
      "Email": "scarter@wstraining.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 6,
      "Proportion to workforce": "6%",
      "No of apprentices in next 12 months": 4,
      "Proportion to workforce in next 12 months": "8%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "East of England Co-op",
      "No of employees": "4500",
      "Sector": "Retail",
      "Contact Name": "Stephen Flurrie",
      "Role": "Head of Learning and Development",
      "Tel number": "01473 786057",
      "Email": "sflurrie@eastofengland.coop",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 19,
      "Proportion to workforce": ">1%",
      "No of apprentices in next 12 months": 75,
      "Proportion to workforce in next 12 months": "2%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "East of England Co-op",
      "No of employees": "4500",
      "Sector": "Retail",
      "Contact Name": "Stephen Flurrie",
      "Role": "Head of Learning and Development",
      "Tel number": "01473 786057",
      "Email": "sflurrie@eastofengland.coop",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "56",
      "No of WE placement in next 12 months": "400",
      "No of EAs in company": "",


  },
      {
          "Organisation": "PWE Recruitment Group Ltd",
      "No of employees": "5",
      "Sector": "Energy",
      "Contact Name": "Stuart Smith",
      "Role": "Managing Director",
      "Tel number": "01502 564892",
      "Email": "stuartsmith@peoplewithenergy.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 0,
      "Proportion to workforce": "0%",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "1/6th",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "PWE Recruitment Group Ltd",
      "No of employees": "5",
      "Sector": "Energy",
      "Contact Name": "Stuart Smith",
      "Role": "Managing Directory",
      "Tel number": "01502 564892",
      "Email": "stuartsmith@peoplewithenergy.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "0",
      "No of WE placement in next 12 months": "1",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Barnes Construction",
      "No of employees": "103",
      "Sector": "Construction",
      "Contact Name": "Ets Mori",
      "Role": "HR Assistant",
      "Tel number": "01473 323923",
      "Email": "emori@barnesgroup.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 2,
      "Proportion to workforce": "2%",
      "No of apprentices in next 12 months": 4,
      "Proportion to workforce in next 12 months": "8%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Barnes Construction",
      "No of employees": "103",
      "Sector": "Construction",
      "Contact Name": "Ets Mori",
      "Role": "HR Assistant",
      "Tel number": "01473 323923",
      "Email": "emori@barnesgroup.co.uk",
      "Type of Pledge": "Wor Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "5",
      "No of WE placement in next 12 months": "3",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Barnes Construction",
      "No of employees": "103",
      "Sector": "Construction",
      "Contact Name": "Ets Mori",
      "Role": "HR Assistant",
      "Tel number": "01473 323923",
      "Email": "emori@barnesgroup.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "9",


  },
      {
          "Organisation": "Albert E Webb & Sons / Webb Truck Equipment / Webb Hydraulic Services",
      "No of employees": "15",
      "Sector": "Engineering",
      "Contact Name": "Samantha Webb",
      "Role": "Administration",
      "Tel number": "01787 377236",
      "Email": "info@extrareach.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 1,
      "Proportion to workforce": "7%",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "15%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Albert E Webb & Sons / Webb Truck Equipment / Webb Hydraulic Services",
      "No of employees": "15",
      "Sector": "Engineering",
      "Contact Name": "Samantha Webb",
      "Role": "Administration",
      "Tel number": "01787 377236",
      "Email": "info@extrareach.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "1",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Howard Nurseries Ltd",
      "No of employees": "45",
      "Sector": "Horticulture",
      "Contact Name": "Christine Howard",
      "Role": "Director",
      "Tel number": "01379 898529",
      "Email": "sales@howardnurseries.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 1,
      "Proportion to workforce": "2%",
      "No of apprentices in next 12 months": 1,
      "Proportion to workforce in next 12 months": "2%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Howard Nurseries Ltd",
      "No of employees": "45",
      "Sector": "Horticulture",
      "Contact Name": "Christine Howard",
      "Role": "Director",
      "Tel number": "01379 898529",
      "Email": "sales@howardnurseries.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "9",
      "No of WE placement in next 12 months": "5",
      "No of EAs in company": "",


  },
      {
          "Organisation": "North Norfolk District Council",
      "No of employees": "305",
      "Sector": "Public",
      "Contact Name": "Janella Hadlow",
      "Role": "Human Resources Business Partner",
      "Tel number": "01263 516024",
      "Email": "janell.hadlow@north-norfolk.gov.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 6,
      "Proportion to workforce": "2%",
      "No of apprentices in next 12 months": 2,
      "Proportion to workforce in next 12 months": "2%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "West Suffolk College",
      "No of employees": "721",
      "Sector": "Futher Education",
      "Contact Name": "Phil Stittle",
      "Role": "Business Development Manager",
      "Tel number": "01284 716398",
      "Email": "phil.stittle@wsc.ac.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 10,
      "Proportion to workforce": "0.7%%",
      "No of apprentices in next 12 months": 10,
      "Proportion to workforce in next 12 months": "1%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "West Suffolk College",
      "No of employees": "721",
      "Sector": "Further Education",
      "Contact Name": "Phil Stittle",
      "Role": "Business Development Manager",
      "Tel number": "01284 716398",
      "Email": "phil.stittle@wsc.ac.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "Multiple",
      "No of WE placement in next 12 months": "Multiple +",
      "No of EAs in company": "",


  },
      {
          "Organisation": "West Suffolk College",
      "No of employees": "721",
      "Sector": "Further Education",
      "Contact Name": "Phil Stittle",
      "Role": "Business Development Manager",
      "Tel number": "01284 716398",
      "Email": "phil.stittle@wsc.ac.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "2",


  },
      {
          "Organisation": "Anglia Farmers Ltd",
      "No of employees": "147",
      "Sector": "Agriculture",
      "Contact Name": "Suzanne Smith",
      "Role": "Head of Organisational Development",
      "Tel number": "01603 881881",
      "Email": "suzanne.smith@angliafarmers.co.uk",
      "Type of Pledge": "Apprenticeships",
      "No of current apprentices": 3,
      "Proportion to workforce": "2%",
      "No of apprentices in next 12 months": 2,
      "Proportion to workforce in next 12 months": "3%",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Anglia Farmers Ltd",
      "No of employees": "147",
      "Sector": "Agriculture",
      "Contact Name": "Suzanne Smith",
      "Role": "Head of Organisational Development",
      "Tel number": "01603 881881",
      "Email": "suzanne.smith@angliafarmers.co.uk",
      "Type of Pledge": "Work Experience",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "2",
      "No of WE placement in next 12 months": "2",
      "No of EAs in company": "",


  },
      {
          "Organisation": "Anglia Farmers Ltd",
      "No of employees": "147",
      "Sector": "Agriculture",
      "Contact Name": "Suzanne Smith",
      "Role": "Head of Organisational Development",
      "Tel number": "01603 881881",
      "Email": "suzanne.smith@angliafarmers.co.uk",
      "Type of Pledge": "Enterprise Adviser",
      "No of current apprentices": "",
  "Proportion to workforce": "",
      "No of apprentices in next 12 months": "",
  "Proportion to workforce in next 12 months": "",
      "No of WE placements in last 12 months": "",
      "No of WE placement in next 12 months": "",
      "No of EAs in company": "3",


  }
  ]
  orgs.each do |org|
    EmployerForm.create!(
      name: org[:"Organisation"],
      number_of_employees: org["No of employees"],
      sector: org[:"Sector"],
      contact_name: org[:"Contact Name"],
        contact_role: org[:"Role"],
        contact_phone: org[:"Tel number"],
      contact_email: org[:"Email"],
        # : org[:"Type of Pledge"],
      number_apprentices: org[:"No of current apprentices"],
        proportion: org[:"Proportion to workforce"].gsub('%', ''),
        future_number_apprentices: org[:"No of apprentices in next 12 months"],
        future_proportion: org[:"Proportion to workforce in next 12 months"].gsub('%', ''),
        work_experience: org[:"No of WE placements in last 12 months"],
      future_work_experience: org[:"No of WE placement in next 12 months"],
      enterprise_adviser: org[:"No of EAs in company"],
    )
  end
  
end